# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_auto_20151226_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
